image: node:18

stages:
  - install
#  - test
  - build
  - deploy

# Install dependencies using Yarn
install_dependencies:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

# Run linting and tests
#run_tests:
#  stage: test
#  script:
#    - yarn lint  # Optional: run this if you have linting configured
#    - yarn test  # Optional: run this if you have tests
#  dependencies:
#   - install_dependencies

# Build the Next.js app
build_nextjs:
  stage: build
  script:
    - yarn build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - .next/


deploy-railway:
  stage: deploy
  image: ubuntu
  only:
    - pushes
    - main
  script:
    - apt-get update && apt-get install -y curl
    - curl -fsSL https://railway.app/install.sh | sh
    - railway login --token=$RAILWAY_TOKEN
    - railway up --service=$RAILWAY_SERVICE_NAME -d
  environment:
    name: development
    # url: https://your-railway-app-url  # Optional: specify the Railway app's public URL

# Pass environment variables from GitLab
variables:
  NEXT_PUBLIC_API_URL: $NEXT_PUBLIC_API_URL 
