image: node:18

stages:
  - install
#  - test
  - build
  - deploy

# Install dependencies using Yarn
install_dependencies:
  stage: install
  script:
    - yarn install
  artifacts:
    paths:
      - node_modules/

# Run linting and tests
#run_tests:
#  stage: test
#  script:
#    - yarn lint  # Optional: run this if you have linting configured
#    - yarn test  # Optional: run this if you have tests
#  dependencies:
#   - install_dependencies

# Build the Next.js app
build_nextjs:
  stage: build
  script:
    - yarn build
  dependencies:
    - install_dependencies
  artifacts:
    paths:
      - .next/