import type { Metadata } from "next";
import HeroWrapper from "@/components/wrappers/hero-wrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-wrap gap-5 justify-between">
            {children}
        </div>
    );
}
