import type { Metadata } from "next";
import HeroWrapper from "@/components/wrappers/hero-wrapper";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-wrap gap-5 justify-between">
            <HeroWrapper
                bgStyles="bg-[url('/assets/bgs/newPostFormBG.png')] bg-right"
                title="Recent tracks"
                description="Provident cupiditate voluptatem et in. Quaerat fugiat ut assumenda excepturi exercitationem quasi. In deleniti eaque aut repudiandae et a id nisi."
            >
                <div className="card shadow-2xl glass w-full min-h-screen">
                    <div className="card-body flex flex-wrap flex-row justify-around gap-5">
                        {children}
                    </div>
                </div>
            </HeroWrapper>
        </div>
    );
}
