export const genres = [
    { title: "Pop",              bg: '/assets/bgs/pop-category.jpg',       icon: "/assets/icons/pop.png" },
    { title: "Blues",            bg: '/assets/bgs/blues-category.jpg',     icon: "/assets/icons/jazz.png"},
    { title: "Classical",        bg: '/assets/bgs/classical-category.jpg', icon: "/assets/icons/hand.png" },
    { title: "Funk",             bg: '/assets/bgs/funk-category.jpg',      icon: "/assets/icons/funk.png"},
    { title: "Soul music",       bg: '/assets/bgs/soul-category.jpg',      icon: "/assets/icons/soul.png" },
    { title: "Hip hop",          bg: '/assets/bgs/hip-hop-category.jpg',   icon: "/assets/icons/hip-hop.png" },
    { title: "Country",          bg: '/assets/bgs/country-category.jpg',   icon: "/assets/icons/acoustic-guitar.png"},
    { title: "Rock",             bg: '/assets/bgs/rock-category.jpg',      icon: "/assets/icons/rock.png"},
    { title: "Electronic",       bg: '/assets/bgs/electronic-category.jpg',icon: "/assets/icons/electronic.png"},
    { title: "Latin",            bg: '/assets/bgs/latin-category.jpg',     icon: "/assets/icons/latin.png" },
    { title: "Jazz",             bg: '/assets/bgs/jazz-category.jpg',      icon: "/assets/icons/jazz.png"},
    { title: "Folk",             bg: '/assets/bgs/folk-category.jpg',      icon: "/assets/icons/folk.png"},
    { title: "Metal",            bg: '/assets/bgs/metal-category.jpg',     icon: "/assets/icons/metal.png" },
];